resources:
- name: concourse-setup
  type: git
  source:
    uri: https://github.com/tobias-johansson/concourse-setup
    branch: master

jobs:
- name: add all
  plan:
  - get: concourse-setup
    trigger: true
  - task: fly
    file: concourse-setup/tasks/add-pipelines.yml
